services:
  openldap:
    image: osixia/openldap:latest
    container_name: institutional-openldap
    environment:
      LDAP_ORGANISATION: "My Org"
      LDAP_DOMAIN: "myorg.local"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
      - "636:636"
    networks:
      - backend

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8090:80"
    depends_on:
      - openldap
    networks:
      - backend

networks:
  backend:
    driver: bridge

