# config.yaml 

# backend environment configs
app:
  name: laclm-dev
  version: v1.1
  environment: development

# backend server deployment configs
server:
  host: localhost
  port: 8080

# databases for operations
database:
  transaction_logs_redis: 
    address:
    password:
    db: 

# logging configurations
logging:
  file:
  max_size:
  max_backups:
  max_age:
  compress:

# filesystem server that needs management
filesystem_servers:
  - path:
    method:
    remote:
      host:
      port:

# authentication information
authentication:
  ldap:

backend_security:
  jwt_expiry:
