# backend environment configs
app:
  name: laclm
  version: v1.1
  debug_mode: true
  session_timeout: 24
  base_path: /mnt
  max_workers: 5

# backend server deployment configs
server:
  host: 0.0.0.0
  port: 8080

# databases for operations
database:
  transaction_log_redis: 
    address: host.docker.internal:6379
    password: ${LACLM_TRANS_REDIS_PASSWORD}
    db: 0
  archival_postgres:
    host: host.docker.internal 
    port: 5432
    user: adityapatil
    password:
    dbname: postgres
    sslmode: disable

# logging configurations
logging:
  file: logs/app.log
  max_size: 100
  max_backups: 5
  max_age: 30
  compress: true

# filesystem server that needs management
filesystem_servers:
  - path: /mnt/beegfs-1
    method: remote
    remote:
      host: 165.232.178.211 
      port: 6593

# authentication information
authentication:
  ldap:
    tls: false
    address: "ldap://openldap:389"
    admin_dn: ${LACLM_LDAP_ADMIN_DN}
    admin_password: ${LACLM_LDAP_ADMIN_PASSWORD}
    search_base: "cn=Princeton Plainsboro Hospital ,dc=myorg,dc=local"

backend_security:
  jwt_secret_token: ${JWT_SECRET_TOKEN}
  jwt_expiry: 1
