# backend environment configs
app:
  name: laclm
  version: v1.1
  debug_mode: true
  session_timeout: 24
  base_path: /mnt

# backend server deployment configs
server:
  host: 0.0.0.0
  port: 8080

# databases for operations
database:
  transaction_log_redis: 
    # address: redis   # Docker service name, not localhost
    address: localhost:6379
    # password: ${LACLM_TRANS_REDIS_PASSWORD}
    password:
    db: 1
  archival_postgres:
    host: 127.0.0.1 
    port: 5432
    user: "adityapatil"
    password:
    dbname: "postgres"
    sslmode: disable

# logging configurations
logging:
  file: logs/app.log
  max_size: 100
  max_backups: 5
  max_age: 30
  compress: true

# filesystem server that needs management
filesystem_servers:
  - path: /mnt/beegfs-1
    method: remote
    remote:
      host: host.docker.internal  # allows container to access host network
      port: 4444

# authentication information
authentication:
  ldap:
    tls: false
    address: "ldap://openldap:389"  # Use the service name from docker-compose
    admin_dn: ${LACLM_LDAP_ADMIN_DN}
    admin_password: ${LACLM_LDAP_ADMIN_PASSWORD}
    search_base: "dc=example,dc=org"

backend_security:
  jwt_secret_token: ${JWT_SECRET_TOKEN}
  jwt_expiry: 1
