# config.yaml 

# backend environment configs
app:
  name: laclm-dev
  version: v1.1
  debug_mode: false 

# backend server deployment configs
server:
  host: localhost
  port: 8080

# databases for operations
database:
  transaction_logs_redis: 
    address: localhost
    password: ${LACLM_TRANS_REDIS_PASSWORD} 
    db: 1

# logging configurations
logging:
  file: logs/app.log
  max_size: 100
  max_backups: 5
  max_age: 30
  compress: true

# filesystem server that needs management
filesystem_servers:
  - path: /mnt/beegfs-1
    method: remote
    remote:
      host: 127.0.0.1
      port: 4444

# authentication information
authentication:
  ldap:
    tls: true 
    address: "ldaps://ldap.example.com"
    admin_dn: ${LACLM_LDAP_ADMIN_DN}
    admin_password: ${LACLM_LDAP_ADMIN_PASSWORD} 

backend_security:
  jwt_secret_key: ${JWT_SECRET_KEY}
  jwt_expiry: 1
