// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SessionsArchive struct {
	ID             uuid.UUID        `json:"id"`
	Username       string           `json:"username"`
	Ip             pgtype.Text      `json:"ip"`
	UserAgent      pgtype.Text      `json:"user_agent"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastActiveAt   pgtype.Timestamp `json:"last_active_at"`
	Expiry         pgtype.Timestamp `json:"expiry"`
	CompletedCount pgtype.Int4      `json:"completed_count"`
	FailedCount    pgtype.Int4      `json:"failed_count"`
	ArchivedAt     pgtype.Timestamp `json:"archived_at"`
}

type TransactionsArchive struct {
	ID        uuid.UUID        `json:"id"`
	SessionID uuid.UUID        `json:"session_id"`
	Status    string           `json:"status"`
	Output    pgtype.Text      `json:"output"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
