// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountTransactionsByOperationPQ(ctx context.Context, arg CountTransactionsByOperationPQParams) (int64, error)
	CountTransactionsByStatusPQ(ctx context.Context, arg CountTransactionsByStatusPQParams) (int64, error)
	CreateTransactionPQ(ctx context.Context, arg CreateTransactionPQParams) (TransactionsArchive, error)
	DeleteSessionPQ(ctx context.Context, id uuid.UUID) error
	DeleteTransactionPQ(ctx context.Context, id uuid.UUID) error
	DeleteTransactionsBySessionPQ(ctx context.Context, sessionID uuid.UUID) error
	GetFailedTransactionsPQ(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error)
	GetPendingTransactionsPQ(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error)
	GetSessionByUsernamePQ(ctx context.Context, username string) ([]SessionsArchive, error)
	GetSessionPQ(ctx context.Context, id uuid.UUID) (SessionsArchive, error)
	GetSuccessfulTransactionsPQ(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error)
	GetTransactionPQ(ctx context.Context, id uuid.UUID) (TransactionsArchive, error)
	GetTransactionStatsPQ(ctx context.Context, sessionID uuid.UUID) (GetTransactionStatsPQRow, error)
	GetTransactionsByOperationPQ(ctx context.Context, arg GetTransactionsByOperationPQParams) ([]TransactionsArchive, error)
	GetTransactionsByPathPQ(ctx context.Context, arg GetTransactionsByPathPQParams) ([]TransactionsArchive, error)
	GetTransactionsBySessionPQ(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error)
	StoreSessionPQ(ctx context.Context, arg StoreSessionPQParams) (SessionsArchive, error)
	UpdateTransactionStatusPQ(ctx context.Context, arg UpdateTransactionStatusPQParams) (TransactionsArchive, error)
}

var _ Querier = (*Queries)(nil)
