// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountTransactionsByStatus(ctx context.Context, arg CountTransactionsByStatusParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (SessionsArchive, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (TransactionsArchive, error)
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteTransaction(ctx context.Context, id uuid.UUID) error
	DeleteTransactionsBySession(ctx context.Context, sessionID uuid.UUID) error
	GetFailedTransactions(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error)
	GetSession(ctx context.Context, id uuid.UUID) (SessionsArchive, error)
	GetSessionByUsername(ctx context.Context, username string) ([]SessionsArchive, error)
	GetSuccessfulTransactions(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (TransactionsArchive, error)
	GetTransactionsBySession(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error)
}

var _ Querier = (*Queries)(nil)
