// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByOperationPQ = `-- name: CountTransactionsByOperationPQ :one
SELECT COUNT(*) FROM transactions_archive
WHERE session_id = $1 AND operation = $2
`

type CountTransactionsByOperationPQParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Operation string    `json:"operation"`
}

func (q *Queries) CountTransactionsByOperationPQ(ctx context.Context, arg CountTransactionsByOperationPQParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByOperationPQ, arg.SessionID, arg.Operation)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByStatusPQ = `-- name: CountTransactionsByStatusPQ :one
SELECT COUNT(*) FROM transactions_archive
WHERE session_id = $1 AND status = $2
`

type CountTransactionsByStatusPQParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Status    string    `json:"status"`
}

func (q *Queries) CountTransactionsByStatusPQ(ctx context.Context, arg CountTransactionsByStatusPQParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByStatusPQ, arg.SessionID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransactionPQ = `-- name: CreateTransactionPQ :one
INSERT INTO transactions_archive (
    id,
    session_id,
    timestamp,
    operation,
    target_path,
    entries,
    status,
    error_msg,
    output,
    executed_by,
    duration_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at
`

type CreateTransactionPQParams struct {
	ID         uuid.UUID          `json:"id"`
	SessionID  uuid.UUID          `json:"session_id"`
	Timestamp  pgtype.Timestamptz `json:"timestamp"`
	Operation  string             `json:"operation"`
	TargetPath string             `json:"target_path"`
	Entries    []byte             `json:"entries"`
	Status     string             `json:"status"`
	ErrorMsg   pgtype.Text        `json:"error_msg"`
	Output     pgtype.Text        `json:"output"`
	ExecutedBy string             `json:"executed_by"`
	DurationMs pgtype.Int8        `json:"duration_ms"`
}

func (q *Queries) CreateTransactionPQ(ctx context.Context, arg CreateTransactionPQParams) (TransactionsArchive, error) {
	row := q.db.QueryRow(ctx, createTransactionPQ,
		arg.ID,
		arg.SessionID,
		arg.Timestamp,
		arg.Operation,
		arg.TargetPath,
		arg.Entries,
		arg.Status,
		arg.ErrorMsg,
		arg.Output,
		arg.ExecutedBy,
		arg.DurationMs,
	)
	var i TransactionsArchive
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.Operation,
		&i.TargetPath,
		&i.Entries,
		&i.Status,
		&i.ErrorMsg,
		&i.Output,
		&i.ExecutedBy,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransactionPQ = `-- name: DeleteTransactionPQ :exec
DELETE FROM transactions_archive
WHERE id = $1
`

func (q *Queries) DeleteTransactionPQ(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransactionPQ, id)
	return err
}

const deleteTransactionsBySessionPQ = `-- name: DeleteTransactionsBySessionPQ :exec
DELETE FROM transactions_archive
WHERE session_id = $1
`

func (q *Queries) DeleteTransactionsBySessionPQ(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransactionsBySessionPQ, sessionID)
	return err
}

const getFailedTransactionsPQ = `-- name: GetFailedTransactionsPQ :many
SELECT id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at FROM transactions_archive
WHERE session_id = $1 AND status = 'failed'
ORDER BY timestamp DESC
`

func (q *Queries) GetFailedTransactionsPQ(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error) {
	rows, err := q.db.Query(ctx, getFailedTransactionsPQ, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionsArchive{}
	for rows.Next() {
		var i TransactionsArchive
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Operation,
			&i.TargetPath,
			&i.Entries,
			&i.Status,
			&i.ErrorMsg,
			&i.Output,
			&i.ExecutedBy,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTransactionsPQ = `-- name: GetPendingTransactionsPQ :many
SELECT id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at FROM transactions_archive
WHERE session_id = $1 AND status = 'pending'
ORDER BY timestamp DESC
`

func (q *Queries) GetPendingTransactionsPQ(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error) {
	rows, err := q.db.Query(ctx, getPendingTransactionsPQ, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionsArchive{}
	for rows.Next() {
		var i TransactionsArchive
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Operation,
			&i.TargetPath,
			&i.Entries,
			&i.Status,
			&i.ErrorMsg,
			&i.Output,
			&i.ExecutedBy,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuccessfulTransactionsPQ = `-- name: GetSuccessfulTransactionsPQ :many
SELECT id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at FROM transactions_archive
WHERE session_id = $1 AND status = 'success'
ORDER BY timestamp DESC
`

func (q *Queries) GetSuccessfulTransactionsPQ(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error) {
	rows, err := q.db.Query(ctx, getSuccessfulTransactionsPQ, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionsArchive{}
	for rows.Next() {
		var i TransactionsArchive
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Operation,
			&i.TargetPath,
			&i.Entries,
			&i.Status,
			&i.ErrorMsg,
			&i.Output,
			&i.ExecutedBy,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionPQ = `-- name: GetTransactionPQ :one
SELECT id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at FROM transactions_archive
WHERE id = $1
`

func (q *Queries) GetTransactionPQ(ctx context.Context, id uuid.UUID) (TransactionsArchive, error) {
	row := q.db.QueryRow(ctx, getTransactionPQ, id)
	var i TransactionsArchive
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.Operation,
		&i.TargetPath,
		&i.Entries,
		&i.Status,
		&i.ErrorMsg,
		&i.Output,
		&i.ExecutedBy,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionStatsPQ = `-- name: GetTransactionStatsPQ :one
SELECT 
    COUNT(*) as total_transactions,
    COUNT(CASE WHEN status = 'success' THEN 1 END) as successful_transactions,
    COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed_transactions,
    COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_transactions,
    AVG(duration_ms) as avg_duration_ms
FROM transactions_archive
WHERE session_id = $1
`

type GetTransactionStatsPQRow struct {
	TotalTransactions      int64   `json:"total_transactions"`
	SuccessfulTransactions int64   `json:"successful_transactions"`
	FailedTransactions     int64   `json:"failed_transactions"`
	PendingTransactions    int64   `json:"pending_transactions"`
	AvgDurationMs          float64 `json:"avg_duration_ms"`
}

func (q *Queries) GetTransactionStatsPQ(ctx context.Context, sessionID uuid.UUID) (GetTransactionStatsPQRow, error) {
	row := q.db.QueryRow(ctx, getTransactionStatsPQ, sessionID)
	var i GetTransactionStatsPQRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.SuccessfulTransactions,
		&i.FailedTransactions,
		&i.PendingTransactions,
		&i.AvgDurationMs,
	)
	return i, err
}

const getTransactionsByOperationPQ = `-- name: GetTransactionsByOperationPQ :many
SELECT id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at FROM transactions_archive
WHERE session_id = $1 AND operation = $2
ORDER BY timestamp DESC
`

type GetTransactionsByOperationPQParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Operation string    `json:"operation"`
}

func (q *Queries) GetTransactionsByOperationPQ(ctx context.Context, arg GetTransactionsByOperationPQParams) ([]TransactionsArchive, error) {
	rows, err := q.db.Query(ctx, getTransactionsByOperationPQ, arg.SessionID, arg.Operation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionsArchive{}
	for rows.Next() {
		var i TransactionsArchive
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Operation,
			&i.TargetPath,
			&i.Entries,
			&i.Status,
			&i.ErrorMsg,
			&i.Output,
			&i.ExecutedBy,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByPathPQ = `-- name: GetTransactionsByPathPQ :many
SELECT id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at FROM transactions_archive
WHERE session_id = $1 AND target_path = $2
ORDER BY timestamp DESC
`

type GetTransactionsByPathPQParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	TargetPath string    `json:"target_path"`
}

func (q *Queries) GetTransactionsByPathPQ(ctx context.Context, arg GetTransactionsByPathPQParams) ([]TransactionsArchive, error) {
	rows, err := q.db.Query(ctx, getTransactionsByPathPQ, arg.SessionID, arg.TargetPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionsArchive{}
	for rows.Next() {
		var i TransactionsArchive
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Operation,
			&i.TargetPath,
			&i.Entries,
			&i.Status,
			&i.ErrorMsg,
			&i.Output,
			&i.ExecutedBy,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsBySessionPQ = `-- name: GetTransactionsBySessionPQ :many
SELECT id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at FROM transactions_archive
WHERE session_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) GetTransactionsBySessionPQ(ctx context.Context, sessionID uuid.UUID) ([]TransactionsArchive, error) {
	rows, err := q.db.Query(ctx, getTransactionsBySessionPQ, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionsArchive{}
	for rows.Next() {
		var i TransactionsArchive
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Operation,
			&i.TargetPath,
			&i.Entries,
			&i.Status,
			&i.ErrorMsg,
			&i.Output,
			&i.ExecutedBy,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatusPQ = `-- name: UpdateTransactionStatusPQ :one
UPDATE transactions_archive
SET 
    status = $2,
    error_msg = $3,
    output = $4,
    duration_ms = $5
WHERE id = $1
RETURNING id, session_id, timestamp, operation, target_path, entries, status, error_msg, output, executed_by, duration_ms, created_at
`

type UpdateTransactionStatusPQParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	ErrorMsg   pgtype.Text `json:"error_msg"`
	Output     pgtype.Text `json:"output"`
	DurationMs pgtype.Int8 `json:"duration_ms"`
}

func (q *Queries) UpdateTransactionStatusPQ(ctx context.Context, arg UpdateTransactionStatusPQParams) (TransactionsArchive, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatusPQ,
		arg.ID,
		arg.Status,
		arg.ErrorMsg,
		arg.Output,
		arg.DurationMs,
	)
	var i TransactionsArchive
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.Operation,
		&i.TargetPath,
		&i.Entries,
		&i.Status,
		&i.ErrorMsg,
		&i.Output,
		&i.ExecutedBy,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}
