// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/acl.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACLEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // "user", "group", "mask", "other"
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`                           // e.g., "alice", "", etc.
	Permissions   string                 `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`                 // e.g., "rw-"
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                           // "add", "modify", "remove"
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLEntry) Reset() {
	*x = ACLEntry{}
	mi := &file_proto_acl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLEntry) ProtoMessage() {}

func (x *ACLEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLEntry.ProtoReflect.Descriptor instead.
func (*ACLEntry) Descriptor() ([]byte, []int) {
	return file_proto_acl_proto_rawDescGZIP(), []int{0}
}

func (x *ACLEntry) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ACLEntry) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *ACLEntry) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *ACLEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ACLEntry) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type ApplyACLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionID string                 `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	TargetPath    string                 `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	Entry         *ACLEntry              `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyACLRequest) Reset() {
	*x = ApplyACLRequest{}
	mi := &file_proto_acl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyACLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyACLRequest) ProtoMessage() {}

func (x *ApplyACLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyACLRequest.ProtoReflect.Descriptor instead.
func (*ApplyACLRequest) Descriptor() ([]byte, []int) {
	return file_proto_acl_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyACLRequest) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *ApplyACLRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ApplyACLRequest) GetEntry() *ACLEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ApplyACLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyACLResponse) Reset() {
	*x = ApplyACLResponse{}
	mi := &file_proto_acl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyACLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyACLResponse) ProtoMessage() {}

func (x *ApplyACLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyACLResponse.ProtoReflect.Descriptor instead.
func (*ApplyACLResponse) Descriptor() ([]byte, []int) {
	return file_proto_acl_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyACLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyACLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_acl_proto protoreflect.FileDescriptor

const file_proto_acl_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/acl.proto\x12\x03acl\"\x9c\x01\n" +
	"\bACLEntry\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12 \n" +
	"\vpermissions\x18\x03 \x01(\tR\vpermissions\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\"}\n" +
	"\x0fApplyACLRequest\x12$\n" +
	"\rtransactionID\x18\x01 \x01(\tR\rtransactionID\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\x12#\n" +
	"\x05entry\x18\x03 \x01(\v2\r.acl.ACLEntryR\x05entry\"F\n" +
	"\x10ApplyACLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2J\n" +
	"\n" +
	"ACLService\x12<\n" +
	"\rApplyACLEntry\x12\x14.acl.ApplyACLRequest\x1a\x15.acl.ApplyACLResponseBYZWgithub.com/PythonHacker24/linux-acl-management-aclapi/internal/grpcserver/protos;protosb\x06proto3"

var (
	file_proto_acl_proto_rawDescOnce sync.Once
	file_proto_acl_proto_rawDescData []byte
)

func file_proto_acl_proto_rawDescGZIP() []byte {
	file_proto_acl_proto_rawDescOnce.Do(func() {
		file_proto_acl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_acl_proto_rawDesc), len(file_proto_acl_proto_rawDesc)))
	})
	return file_proto_acl_proto_rawDescData
}

var file_proto_acl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_acl_proto_goTypes = []any{
	(*ACLEntry)(nil),         // 0: acl.ACLEntry
	(*ApplyACLRequest)(nil),  // 1: acl.ApplyACLRequest
	(*ApplyACLResponse)(nil), // 2: acl.ApplyACLResponse
}
var file_proto_acl_proto_depIdxs = []int32{
	0, // 0: acl.ApplyACLRequest.entry:type_name -> acl.ACLEntry
	1, // 1: acl.ACLService.ApplyACLEntry:input_type -> acl.ApplyACLRequest
	2, // 2: acl.ACLService.ApplyACLEntry:output_type -> acl.ApplyACLResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_acl_proto_init() }
func file_proto_acl_proto_init() {
	if File_proto_acl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_acl_proto_rawDesc), len(file_proto_acl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_acl_proto_goTypes,
		DependencyIndexes: file_proto_acl_proto_depIdxs,
		MessageInfos:      file_proto_acl_proto_msgTypes,
	}.Build()
	File_proto_acl_proto = out.File
	file_proto_acl_proto_goTypes = nil
	file_proto_acl_proto_depIdxs = nil
}
