# .github/workflows/gofmt.yml
# .github/workflows/lint.yml
name: Lint Check

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Run make lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run lint
        run: make lint
